server:
  port: 9100

# \u670D\u52A1\u540D\u79F0
spring:
  application:
    name: config-server
  #git\u914D\u7F6E
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kangswx/config-cloud.git
          username: kangswx
          password: *
          timeout: 5
          default-label: master

# \u6CE8\u518C\u4E2D\u5FC3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
